"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Ranks = void 0;
// https://github.com/giorgi-o/CrossPlatformPlaying/blob/1052dae6e1007c020f6f762cab35989214bcdb92/CrossPlatformPlaying.plugin.js#L1796
var Ranks;
(function (Ranks) {
    Ranks[Ranks["UNRANKED"] = 0] = "UNRANKED";
    Ranks[Ranks["Unused1"] = 1] = "Unused1";
    Ranks[Ranks["Unused2"] = 2] = "Unused2";
    Ranks[Ranks["IRON1"] = 3] = "IRON1";
    Ranks[Ranks["IRON2"] = 4] = "IRON2";
    Ranks[Ranks["IRON3"] = 5] = "IRON3";
    Ranks[Ranks["BRONZE1"] = 6] = "BRONZE1";
    Ranks[Ranks["BRONZE2"] = 7] = "BRONZE2";
    Ranks[Ranks["BRONZE3"] = 8] = "BRONZE3";
    Ranks[Ranks["SILVER1"] = 9] = "SILVER1";
    Ranks[Ranks["SILVER2"] = 10] = "SILVER2";
    Ranks[Ranks["SILVER3"] = 11] = "SILVER3";
    Ranks[Ranks["GOLD1"] = 12] = "GOLD1";
    Ranks[Ranks["GOLD2"] = 13] = "GOLD2";
    Ranks[Ranks["GOLD3"] = 14] = "GOLD3";
    Ranks[Ranks["PLATINUM1"] = 15] = "PLATINUM1";
    Ranks[Ranks["PLATINUM2"] = 16] = "PLATINUM2";
    Ranks[Ranks["PLATINUM3"] = 17] = "PLATINUM3";
    Ranks[Ranks["DIAMOND1"] = 18] = "DIAMOND1";
    Ranks[Ranks["DIAMOND2"] = 19] = "DIAMOND2";
    Ranks[Ranks["DIAMOND3"] = 20] = "DIAMOND3";
    Ranks[Ranks["ASCENDANT1"] = 21] = "ASCENDANT1";
    Ranks[Ranks["ASCENDANT2"] = 22] = "ASCENDANT2";
    Ranks[Ranks["ASCENDANT3"] = 23] = "ASCENDANT3";
    Ranks[Ranks["IMMORTAL1"] = 24] = "IMMORTAL1";
    Ranks[Ranks["IMMORTAL2"] = 25] = "IMMORTAL2";
    Ranks[Ranks["IMMORTAL3"] = 26] = "IMMORTAL3";
    Ranks[Ranks["RADIANT"] = 27] = "RADIANT";
})(Ranks = exports.Ranks || (exports.Ranks = {}));
